# Generated by Django 3.2.7 on 2021-09-08 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubs', '0001_initial'),
        ('accounts', '0002_alter_customusuario_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='ubs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubs.ubs'),
        ),
    ]
