# Generated by Django 3.1.5 on 2021-09-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50, verbose_name='nome')),
            ],
            options={
                'verbose_name_plural': 'cidades',
                'db_table': 'cidade',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50, verbose_name='nome')),
                ('sigla', models.TextField(max_length=2, verbose_name='sigla')),
            ],
            options={
                'verbose_name_plural': 'estados',
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Ubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50, verbose_name='nome')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.cidade')),
            ],
            options={
                'verbose_name_plural': 'ubs',
                'db_table': 'ubs',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.estado'),
        ),
    ]
