# Generated by Django 3.2.7 on 2021-09-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='sigla',
            field=models.CharField(max_length=2, verbose_name='sigla'),
        ),
        migrations.AlterField(
            model_name='ubs',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
