# Generated by Django 3.1.5 on 2021-09-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='id',
            field=models.AutoField(db_column='id_cidade', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estado',
            name='id',
            field=models.AutoField(db_column='id_estado', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ubs',
            name='id',
            field=models.AutoField(db_column='id_ubs', primary_key=True, serialize=False),
        ),
    ]
